"""ParaView-based CFD heatmap rendering for 3D Cp/Cf visualization.

Generates publication-quality renders of surface pressure coefficient (Cp)
and skin friction coefficient (Cf) mapped onto the 3D aircraft geometry.

Requires ParaView's pvpython (Python scripting interface). The pipeline:
1. Load SU2 surface_flow.csv (or converted VTK/VTU)
2. Map Cp/Cf scalar fields onto the surface mesh
3. Apply color maps (blue-white-red for Cp, sequential for Cf)
4. Render from 4 standard views (isometric, front, top, right)
5. Export PNG renders

If ParaView is not available, falls back to matplotlib 2D scatter plots
of Cp and Cf (degraded but still informative).
"""

from __future__ import annotations

import csv
import logging
import math
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass
class HeatmapConfig:
    """Configuration for heatmap rendering."""

    # Views to render
    views: list[str] = None  # type: ignore[assignment]
    image_width: int = 1920
    image_height: int = 1080

    # Color map ranges (None = auto-scale)
    cp_range: Optional[tuple[float, float]] = (-2.0, 1.0)
    cf_range: Optional[tuple[float, float]] = None

    # Background
    background_color: tuple[float, float, float] = (0.05, 0.05, 0.1)

    def __post_init__(self) -> None:
        if self.views is None:
            self.views = ["isometric", "front", "top", "right"]


# ---------------------------------------------------------------------------
# ParaView availability check
# ---------------------------------------------------------------------------


def paraview_available() -> bool:
    """Check if pvpython is available on PATH."""
    return shutil.which("pvpython") is not None


# ---------------------------------------------------------------------------
# Surface data to VTK conversion
# ---------------------------------------------------------------------------


def surface_csv_to_vtk(
    csv_path: Path,
    vtk_path: Path,
) -> Path:
    """Convert AeroForge surface CSV to VTK PolyData format.

    The CSV has columns: x, y, z, Cp, Cf, Cf_x, Cf_y, Cf_z, pressure
    """
    points: list[tuple[float, float, float]] = []
    cp_vals: list[float] = []
    cf_vals: list[float] = []
    pressure_vals: list[float] = []

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                x = float(row.get("x", 0))
                y = float(row.get("y", 0))
                z = float(row.get("z", 0))
                cp = float(row.get("Cp", row.get("cp", 0)))
                cf = float(row.get("Cf", row.get("cf", 0)))
                p = float(row.get("pressure", row.get("Pressure", 0)))
            except (ValueError, TypeError):
                continue
            points.append((x, y, z))
            cp_vals.append(cp)
            cf_vals.append(cf)
            pressure_vals.append(p)

    if not points:
        raise ValueError(f"No valid points in {csv_path}")

    # Write VTK legacy format (PolyData with point scalars)
    vtk_path.parent.mkdir(parents=True, exist_ok=True)
    n = len(points)

    with open(vtk_path, "w", encoding="utf-8") as f:
        f.write("# vtk DataFile Version 3.0\n")
        f.write("AeroForge CFD Surface Data\n")
        f.write("ASCII\n")
        f.write("DATASET POLYDATA\n")
        f.write(f"POINTS {n} float\n")
        for x, y, z in points:
            f.write(f"{x} {y} {z}\n")

        # Vertices (each point is a vertex)
        f.write(f"VERTICES {n} {n * 2}\n")
        for i in range(n):
            f.write(f"1 {i}\n")

        # Point data
        f.write(f"POINT_DATA {n}\n")

        f.write("SCALARS Cp float 1\n")
        f.write("LOOKUP_TABLE default\n")
        for v in cp_vals:
            f.write(f"{v}\n")

        f.write("SCALARS Cf float 1\n")
        f.write("LOOKUP_TABLE default\n")
        for v in cf_vals:
            f.write(f"{v}\n")

        f.write("SCALARS Pressure float 1\n")
        f.write("LOOKUP_TABLE default\n")
        for v in pressure_vals:
            f.write(f"{v}\n")

    logger.info("Wrote VTK file with %d points to %s", n, vtk_path)
    return vtk_path


# ---------------------------------------------------------------------------
# ParaView script generation
# ---------------------------------------------------------------------------

_PVPYTHON_SCRIPT_TEMPLATE = '''
"""ParaView batch rendering script — generated by AeroForge."""
import sys
from paraview.simple import *

# Load data
reader = LegacyVTKReader(FileNames=['{vtk_path}'])

# Create render view
view = CreateRenderView()
view.ViewSize = [{width}, {height}]
view.Background = [{bg_r}, {bg_g}, {bg_b}]

# Display settings
display = Show(reader, view)
display.Representation = 'Surface'

# Camera positions for standard views
VIEWS = {{
    "isometric": ([1, 1, 0.5], [0, 0, 0], [0, 0, 1]),
    "front":     ([1, 0, 0],   [0, 0, 0], [0, 0, 1]),
    "top":       ([0, 0, 1],   [0, 0, 0], [0, 1, 0]),
    "right":     ([0, -1, 0],  [0, 0, 0], [0, 0, 1]),
}}

# Scalar fields to render
FIELDS = {{
    "Cp": {{
        "range": [{cp_min}, {cp_max}],
        "colormap": "Cool to Warm",
    }},
    "Cf": {{
        "range": [{cf_min}, {cf_max}],
        "colormap": "Viridis (matplotlib)",
    }},
}}

for field_name, field_cfg in FIELDS.items():
    ColorBy(display, ('POINTS', field_name))
    ctf = GetColorTransferFunction(field_name)
    ctf.RescaleTransferFunction(field_cfg["range"][0], field_cfg["range"][1])
    ctf.ApplyPreset(field_cfg["colormap"], True)

    # Color bar
    cbar = GetScalarBar(ctf, view)
    cbar.Title = field_name
    cbar.ComponentTitle = ''
    cbar.Visibility = 1

    for view_name, (pos, focal, up) in VIEWS.items():
        # Scale position to fit geometry
        bounds = reader.GetDataInformation().GetBounds()
        max_dim = max(bounds[1]-bounds[0], bounds[3]-bounds[2], bounds[5]-bounds[4])
        scale = max_dim * 2.5

        camera = view.GetActiveCamera()
        center = [(bounds[0]+bounds[1])/2, (bounds[2]+bounds[3])/2, (bounds[4]+bounds[5])/2]
        camera.SetPosition(center[0]+pos[0]*scale, center[1]+pos[1]*scale, center[2]+pos[2]*scale)
        camera.SetFocalPoint(*center)
        camera.SetViewUp(*up)
        view.ResetCamera()

        output_path = '{output_dir}/' + f'{{field_name}}_{{view_name}}.png'
        SaveScreenshot(output_path, view, ImageResolution=[{width}, {height}])
        print(f"Saved: {{output_path}}")

    cbar.Visibility = 0

print("PARAVIEW_RENDER_COMPLETE")
'''


def _generate_pvpython_script(
    vtk_path: Path,
    output_dir: Path,
    config: HeatmapConfig,
) -> str:
    """Generate the pvpython script content."""
    cp_min, cp_max = config.cp_range or (-2.0, 1.0)
    cf_min, cf_max = config.cf_range or (0.0, 0.01)

    return _PVPYTHON_SCRIPT_TEMPLATE.format(
        vtk_path=str(vtk_path).replace("\\", "/"),
        output_dir=str(output_dir).replace("\\", "/"),
        width=config.image_width,
        height=config.image_height,
        bg_r=config.background_color[0],
        bg_g=config.background_color[1],
        bg_b=config.background_color[2],
        cp_min=cp_min,
        cp_max=cp_max,
        cf_min=cf_min,
        cf_max=cf_max,
    )


# ---------------------------------------------------------------------------
# Matplotlib fallback (when ParaView is not available)
# ---------------------------------------------------------------------------


def _render_matplotlib_fallback(
    csv_path: Path,
    output_dir: Path,
    config: HeatmapConfig,
) -> list[Path]:
    """Render 2D scatter heatmaps using matplotlib as fallback."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors

    points_x: list[float] = []
    points_y: list[float] = []
    points_z: list[float] = []
    cp_vals: list[float] = []
    cf_vals: list[float] = []

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                points_x.append(float(row.get("x", 0)))
                points_y.append(float(row.get("y", 0)))
                points_z.append(float(row.get("z", 0)))
                cp_vals.append(float(row.get("Cp", row.get("cp", 0))))
                cf_vals.append(float(row.get("Cf", row.get("cf", 0))))
            except (ValueError, TypeError):
                continue

    if not points_x:
        logger.warning("No points for matplotlib fallback rendering")
        return []

    output_dir.mkdir(parents=True, exist_ok=True)
    outputs: list[Path] = []

    # View projections: (x_data, y_data, xlabel, ylabel, view_name)
    projections = [
        (points_x, points_z, "X (streamwise)", "Z (vertical)", "side"),
        (points_y, points_z, "Y (spanwise)", "Z (vertical)", "front"),
        (points_x, points_y, "X (streamwise)", "Y (spanwise)", "top"),
    ]

    for field_name, vals, cmap_name in [("Cp", cp_vals, "coolwarm"), ("Cf", cf_vals, "viridis")]:
        vmin = config.cp_range[0] if field_name == "Cp" and config.cp_range else min(vals)
        vmax = config.cp_range[1] if field_name == "Cp" and config.cp_range else max(vals)
        if field_name == "Cf" and config.cf_range:
            vmin, vmax = config.cf_range

        for xdata, ydata, xlabel, ylabel, view_name in projections:
            fig, ax = plt.subplots(1, 1, figsize=(16, 9), dpi=120)
            fig.patch.set_facecolor("#0d0d1a")
            ax.set_facecolor("#0d0d1a")

            sc = ax.scatter(
                xdata, ydata, c=vals, cmap=cmap_name,
                vmin=vmin, vmax=vmax, s=1, alpha=0.8,
            )
            cbar = plt.colorbar(sc, ax=ax, shrink=0.8)
            cbar.set_label(field_name, color="white")
            cbar.ax.yaxis.set_tick_params(color="white")
            plt.setp(cbar.ax.yaxis.get_ticklabels(), color="white")

            ax.set_xlabel(xlabel, color="white")
            ax.set_ylabel(ylabel, color="white")
            ax.set_title(f"{field_name} — {view_name} view", color="white", fontsize=14)
            ax.tick_params(colors="white")
            ax.set_aspect("equal")

            path = output_dir / f"{field_name}_{view_name}.png"
            fig.savefig(path, bbox_inches="tight", facecolor=fig.get_facecolor())
            plt.close(fig)
            outputs.append(path)
            logger.info("Saved matplotlib heatmap: %s", path)

    return outputs


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def render_heatmaps(
    surface_csv: Path,
    output_dir: Path,
    config: Optional[HeatmapConfig] = None,
) -> list[Path]:
    """Render Cp/Cf heatmaps on the 3D aircraft geometry.

    Uses ParaView (pvpython) if available, otherwise falls back to
    matplotlib 2D scatter plots.

    Args:
        surface_csv: Path to the AeroForge surface CSV (x,y,z,Cp,Cf,...)
        output_dir: Directory for output PNG renders
        config: Rendering configuration

    Returns:
        List of paths to generated PNG files.

    Raises:
        FileNotFoundError: If surface_csv doesn't exist (hard stop).
        ValueError: If surface_csv contains no valid points (hard stop).
    """
    surface_csv = Path(surface_csv)
    output_dir = Path(output_dir)
    config = config or HeatmapConfig()

    if not surface_csv.exists():
        raise FileNotFoundError(
            f"Surface flow data not found: {surface_csv}. "
            f"CFD heatmap rendering requires surface_flow.csv from SU2 — HARD STOP."
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    if paraview_available():
        return _render_paraview(surface_csv, output_dir, config)
    else:
        logger.warning(
            "ParaView (pvpython) not found — using matplotlib fallback. "
            "Install ParaView for full 3D heatmap renders."
        )
        return _render_matplotlib_fallback(surface_csv, output_dir, config)


def _render_paraview(
    surface_csv: Path,
    output_dir: Path,
    config: HeatmapConfig,
) -> list[Path]:
    """Render using ParaView pvpython."""
    # Convert CSV to VTK
    vtk_path = output_dir / "surface_data.vtk"
    surface_csv_to_vtk(surface_csv, vtk_path)

    # Generate and run pvpython script
    script_content = _generate_pvpython_script(vtk_path, output_dir, config)
    script_path = output_dir / "_render_heatmaps.py"
    script_path.write_text(script_content, encoding="utf-8")

    try:
        result = subprocess.run(
            ["pvpython", str(script_path)],
            capture_output=True,
            text=True,
            timeout=300,
            cwd=str(output_dir),
        )
        if result.returncode != 0:
            logger.error("pvpython failed: %s", result.stderr[:500])
            logger.warning("Falling back to matplotlib")
            return _render_matplotlib_fallback(surface_csv, output_dir, config)

        if "PARAVIEW_RENDER_COMPLETE" not in result.stdout:
            logger.warning("ParaView script may not have completed fully")

    except subprocess.TimeoutExpired:
        logger.error("pvpython timed out after 300s — falling back to matplotlib")
        return _render_matplotlib_fallback(surface_csv, output_dir, config)
    except FileNotFoundError:
        logger.warning("pvpython not found at runtime — falling back to matplotlib")
        return _render_matplotlib_fallback(surface_csv, output_dir, config)

    # Collect generated PNGs
    outputs: list[Path] = []
    for png in sorted(output_dir.glob("*.png")):
        if png.stat().st_size > 0:
            outputs.append(png)

    if not outputs:
        logger.warning("ParaView produced no output PNGs — falling back to matplotlib")
        return _render_matplotlib_fallback(surface_csv, output_dir, config)

    logger.info("ParaView rendered %d heatmap images", len(outputs))
    return outputs
