"""SU2 CFD pipeline for AeroForge.

Handles mesh generation (Gmsh), and SU2 configuration, and execution for
 virtual wind tunnel analysis on RC aircraft geomet.

Pipeline: STEP → Gmsh mesh → SU2 config → SU2_CFD → Results extraction
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class CFDConfig:
    """SU2 simulation configuration."""
    solver_type: str = "EULER"  # EULER, INC_EULER, RANS
    turbulence_model: str = "SA"  # SA, SST
    freestream_velocity: float = 10.0  # m/s
    freestream_temperature: float = 288.15  # K
    reynolds_number: float = 100000.0
    reynolds_length: float = 0.17  # m (chord)
    mach_number: float = 0.03  # ~10 m/s / 343 m/s
    alpha_range: tuple[float, float] = (-5.0, 15.0)
    alpha_step: float = 1.0
    sideslip_range: tuple[float, float] = (-5.0, 5.0)
    sideslip_step: float = 2.5
    mesh_file: str = "mesh.su2"
    output_dir: str = "cfd_results"
    use_gpu: bool = True
    num_processors: int = 1
    farfield_distance: float = 20.0  # chord multiples
    mesh_size: str = "COARSE"  # COARSE, MEDIUM, FINE

    def to_cfg_string(self) -> str:
        """Generate SU2 configuration file content."""
        lines = [
            "% SU2 Configuration - Auto-generated by AeroForge CFD Pipeline",
            f"SOLVER= {self.solver_type}",
            f"",
            f"% --- Flow conditions ---",
            f"MATH_PROBLEM= DIRECT",
            f"RESTART_SOL= NO",
            f"SYSTEM_MEASUREMENT= YES",
            f"SCREEN_OUTPUT= YES",
            f"HISTORY_OUTPUT= YES",
            f"",
            f"% --- Freestream ---",
            f"FREESTREAM_VELOCITY= ({self.freestream_velocity}, 0.0, 0.0)",
            f"FREESTREAM_TEMPERATURE= {self.freestream_temperature}",
            f"FREESTREAM_PRESSURE= 101325.0",
            f"",
            f"% --- Model ---",
            f"FLUID_MODEL= INC_IDEAL_GAS",
            f"AOA= 5.0",
            f"SIDESLIP_ANGLE= 0.0",
            f"INITIAL_ALPHA= 0.0",
            f"",
            f"% --- Reynolds ---",
            f"REYNOLDS_NUMBER= {self.reynolds_number}",
            f"REYNOLDS_LENGTH= {self.reynolds_length}",
            f"",
            f"% --- Reference ---",
            f"REF_ORIGIN= 0.0 0.0 0.0",
            f"REF_LENGTH= {self.reynolds_length}",
            f"REF_AREA= 1.0",
            f"",
            f"% --- Mesh ---",
            f"MESH_FILENAME= {self.mesh_file}",
            f"MESH_FORMAT= SU2",
            f",
            f"% --- Output ---",
            f"OUTPUT_FILES= (restart, flow, surface_flow)",
            f"CONV_FILENAME= {self.output_dir}/restart_flow.dat",
            f"SOLUTION_FLOW_FILENAME= {self.output_dir}/flow.dat",
            f"SURFACE_FLOW_FILENAME= {self.output_dir}/surface_flow.csv",
            f"HISTORY_FILENAME= {self.output_dir}/history.csv",
            f"",
            f"% --- Convergence ---",
            f"CONV_CRITERIA= RESidual",
            f"CONV_FIELD= DENSITY",
            f"CONV_RESIDUAL_MINVAL= -8",
            f"CONV_ITER= 1000",
            f"",
            f"% --- Boundary conditions ---",
            f"MARKER_FARFIELD= ( farfield )",
            f"MARKER_SYM= ( symmetry )",
            f"MARKER_AIRCRAFT= ( aircraft )",
            f"FARFIELD_KIND= FARfield Riemann",
            f"SYMMETRY_KIND= Symmetry Plane",
        ]

        if self.solver_type == "RANS":
            if self.turbulence_model == "SA":
                lines.extend([
                    f"TURBULENCE_MODEL= SA",
                    f"SA_OPTIONS= SA_NEGATIVE",
                ])
            elif self.turbulence_model == "SST":
                lines.extend([
                    f"TURBULENCE_MODEL= SST",
                    f"SST_OPTIONS= SST_2003",
                ])
            lines.extend([
                f"WALL_FUNCTIONS= STANDARD_WALL",
                f"WALL_DISTANCE= {0.17 / (self.reynolds_number * 300)}",
            ])

        return "\n".join(lines)


@dataclass
class CFDResult:
    """Results from a CFD analysis run."""
    alpha: float
    cl: float
    cd: float
    cm: float
    cl_alpha: Optional[float] = None  # dCL/da
    l_d: Optional[float] = None  # L/D ratio
    cd_induced: Optional[float] = None
    cd_parasitic: Optional[float] = None
    convergence: Optional[str] = None
    iterations: Optional[int] = None


def generate_mesh(
    step_file: str | Path,
    output_file: str | Path,
    farfield_mult: float = 20.0,
    boundary_layer: bool = True,
    y_plus: float = 1.0,
    mesh_size_factor: float = 1.0,
) -> Path:
    """Generate SU2-compatible volume mesh from STEP geometry using Gmsh.

    Args:
        step_file: Path to STEP geometry file
        output_file: Path to output .su2 mesh file
        farfield_mult: Farfield distance as multiple of max chord
        boundary_layer: Whether to add boundary layer inflation
        y_plus: Target y+ value (for RANS)
        mesh_size_factor: Mesh size scaling (1.0 = default)

    Returns:
        Path to the generated mesh file
    """
    import gmsh

    gmsh.initialize()
    gmsh.merge(str(step_file))

    # Get bounding box for sizing
    dim = gmsh.model.getDimension(3)
    max_chord = max(dim[0], dim[1], dim[2])

    # Farfield box
    ff = max_chord * farfield_mult
    # Add farfield box and boundary definitions

    # Mesh sizing
    base_size = max_chord * 0.02 * mesh_size_factor  # 2% of max chord

    # Set mesh sizes
    gmsh.option.setMeshSize(base_size)
    gmsh.option.setMeshSizeMin(base_size * 0.1)
    gmsh.option.setMeshSizeMax(base_size * 5)

    if boundary_layer:
        # Boundary layer - calculate first cell height for target y+
        # y+ = y_first * u_tau / nu  => y_first = y+ * nu / u_tau
        # Approximate: at Re=100k, y+ = 1, first cell ~ 0.1mm
        n_layers = 25
        growth_rate = 1.2
        first_height = base_size * 0.01  # Approximate
        gmsh.option.setBoundaryLayer(
            "aircraft", n_layers, first_height, growth_rate
        )

    # Generate 3D mesh
    gmsh.model.mesh.generate(3)

    # Export in SU2 format
    gmsh.write(str(output_file))
    gmsh.finalize()

    return output_file


def run_su2(
    config_file: str | Path,
    su2_executable: str = "SU2_CFD",
    timeout: int = 3600,
) -> dict:
    """Run SU2 CFD solver.

    Args:
        config_file: Path to SU2 .cfg file
        su2_executable: Name or path of SU2 executable
        timeout: Timeout in seconds

    Returns:
        Dict with stdout, stderr, and return code
    """
    result = subprocess.run(
        [su2_executable, str(config_file)],
        capture_output=True,
        text=True,
        timeout=timeout,
        cwd=str(Path(config_file).parent),
    )
    return {
        "stdout": result.stdout,
        "stderr": result.stderr,
        "returncode": result.returncode,
    }


def extract_polar(history_csv: str | Path) -> list[CFDResult]:
    """Extract polar data from SU2 history CSV output.

    Args:
        history_csv: Path to SU2 history.csv file

    Returns:
        List of CFDResult for each converged angle
    """
    results: list[CFDResult] = []

    with open(history_csv) as f:
        header = f.readline().strip().split(",")
        # Find column indices
        alpha_idx = header.index("AOA")
        cl_idx = header.index("CL")
        cd_idx = header.index("CD")
        cm_idx = None
        for name in header:
            if "CMz" in name or "MOMENT_Z" in name:
                cm_idx = header.index(name)
                break

        for line in f:
            vals = line.strip().split(",")
            if len(vals) <= max(alpha_idx, cl_idx, cd_idx):
                continue
            try:
                alpha = float(vals[alpha_idx])
                cl = float(vals[cl_idx])
                cd = float(vals[cd_idx])
                cm = float(vals[cm_idx]) if cm_idx else 0.0
            except (ValueError, IndexError):
                continue

            ld = cl / cd if cd > 0 else None
            results.append(CFDResult(
                alpha=alpha, cl=cl, cd=cd, cm=cm, l_d=ld,
            ))

    return results


def run_polar_sweep(
    step_file: str | Path,
    output_dir: str | Path,
    alpha_range: tuple[float, float] = (-5.0, 15.0),
    alpha_step: float = 1.0,
    solver_type: str = "EULER",
    reynolds_number: float = 100000.0,
    chord: float = 0.17,
    speed: float = 10.0,
) -> list[CFDResult]:
    """Run a complete alpha sweep on a geometry.

    This is the main entry point for virtual wind tunnel testing.

    Args:
        step_file: Path to STEP geometry
        output_dir: Directory for results
        alpha_range: (min_alpha, max_alpha)
        alpha_step: Angle increment
        solver_type: EULER or RANS
        reynolds_number: Reynolds number
        chord: Reference chord length in meters
        speed: Freestream velocity in m/s

    Returns:
        List of CFDResult for each angle
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    mesh_file = output_dir / "mesh.su2"

    # Generate mesh
    generate_mesh(step_file, mesh_file)

    all_results: list[CFDResult] = []

    alpha_min, alpha_max = alpha_range
    alphas = []
    a = alpha_min
    while a <= alpha_max + 0.001:
        alphas.append(round(a, 2))
        a += alpha_step

    for alpha in alphas:
        config = CFDConfig(
            solver_type=solver_type,
            reynolds_number=reynolds_number,
            reynolds_length=chord,
            freestream_velocity=speed,
            mesh_file=str(mesh_file),
            output_dir=str(output_dir / f"alpha_{alpha:.1f}"),
        )
        config.alpha_range = (alpha, alpha)
        config.alpha_step = 0.0

        cfg_file = output_dir / f"alpha_{alpha:.1f}" / "config.cfg"
        cfg_file.parent.mkdir(parents=True, exist_ok=True)
        cfg_file.write_text(config.to_cfg_string())

        result = run_su2(cfg_file)

        if result["returncode"] == 0:
            history = output_dir / f"alpha_{alpha:.1f}" / "history.csv"
            if history.exists():
                polar = extract_polar(history)
                if polar:
                    all_results.extend(polar)

    return all_results
