"""Web search and content scraping for the RAG pipeline.

Query generation is LLM-driven, not hardcoded. The scraper receives
explicit queries (generated by the agent from the mission prompt) and
fetches/chunks the results.
"""

from __future__ import annotations

import logging
import re
from typing import Any

from .chunker import Chunk, DocumentChunker
from .config import RAGConfig

logger = logging.getLogger(__name__)


class DomainScraper:
    """Scrape web content and chunk it for the RAG database.

    Query generation is NOT done here. The calling agent or orchestrator
    decides what to search for based on the user's mission prompt. This
    class only executes the searches and chunks the results.
    """

    def __init__(
        self,
        config: RAGConfig | None = None,
        chunker: DocumentChunker | None = None,
    ) -> None:
        self._config = config or RAGConfig()
        self._chunker = chunker or DocumentChunker()

    def build_baseline_queries(self, mission_prompt: str) -> list[str]:
        """Generate minimal baseline queries from the raw mission prompt.

        These are intentionally generic — just the mission prompt words
        combined with standard research angles. The LLM agent should
        generate better, more specific queries on its own.
        """
        prompt_clean = mission_prompt.strip()[:200]
        queries = [
            f"{prompt_clean} design specifications",
            f"{prompt_clean} similar existing designs",
            f"{prompt_clean} regulations rules standards",
            f"{prompt_clean} construction techniques materials",
            f"{prompt_clean} aerodynamic performance data",
        ]
        return queries[: self._config.search_queries_per_domain]

    def scrape_url(self, url: str) -> list[Chunk]:
        """Fetch and chunk a single URL. Returns empty list on failure."""
        try:
            import httpx

            response = httpx.get(url, timeout=15, follow_redirects=True)
            response.raise_for_status()
            content_type = response.headers.get("content-type", "")

            if "html" in content_type:
                chunks = self._chunker.chunk_html(
                    response.text,
                    {"source_type": "web", "source_url": url},
                )
            else:
                chunks = self._chunker.chunk_plain(
                    response.text,
                    {"source_type": "web", "source_url": url},
                )
            return chunks
        except Exception as exc:
            logger.debug("Failed to scrape %s: %s", url, exc)
            return []

    def scrape_search_results(
        self,
        queries: list[str],
        max_results_per_query: int = 3,
    ) -> list[Chunk]:
        """Run web searches and scrape top results.

        Best-effort — returns empty list if no search backend is available.
        """
        all_chunks: list[Chunk] = []
        seen_urls: set[str] = set()

        for query in queries:
            urls = self._web_search(query, max_results_per_query)
            for url in urls:
                if url in seen_urls:
                    continue
                seen_urls.add(url)
                chunks = self.scrape_url(url)
                all_chunks.extend(chunks)
                if len(all_chunks) >= self._config.max_web_results * 5:
                    return all_chunks

        logger.info(
            "Scraped %d chunks from %d unique URLs",
            len(all_chunks),
            len(seen_urls),
        )
        return all_chunks

    @staticmethod
    def _web_search(query: str, max_results: int = 3) -> list[str]:
        """Best-effort web search. Returns URLs or empty list."""
        try:
            import httpx

            response = httpx.get(
                "https://html.duckduckgo.com/html/",
                params={"q": query},
                headers={"User-Agent": "AeroForge-RAG/1.0"},
                timeout=10,
                follow_redirects=True,
            )
            urls = re.findall(r'href="(https?://[^"]+)"', response.text)
            filtered = [
                u for u in urls
                if "duckduckgo.com" not in u and "duck.co" not in u
            ]
            return filtered[:max_results]
        except Exception:
            return []
